// Generated by pnpm worker:build-context -- always runs before tsup in worker:build
import { SYSTEM_PROMPT } from "./docs-context.js";

const ALLOWED_MODELS = [
  "gemini-2.5-flash",
  "gemini-2.5-flash-lite",
  "gemma-4-26b-a4b-it",
];

const DEFAULT_MODEL = ALLOWED_MODELS[0];

// Allowed origins for CORS.
// Production: GitHub Pages static site host (all routes share this origin).
// Development: local Next.js dev server.
const CORS_ORIGINS = ["https://burglekitt.github.io", "http://localhost:3000"];

function getCorsHeaders(origin: string | null): Record<string, string> {
  const allowed =
    origin !== null && CORS_ORIGINS.includes(origin) ? origin : CORS_ORIGINS[0];
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    Vary: "Origin",
  };
}

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models";

type GeminiPart = { text: string };
type GeminiContent = { role: string; parts: GeminiPart[] };

function toGeminiContents(
  messages: Array<{ role: string; content: string }>,
): GeminiContent[] {
  return messages.map((m) => ({
    role: m.role === "assistant" ? "model" : "user",
    parts: [{ text: m.content }],
  }));
}

export default {
  async fetch(request: Request, env: Record<string, string>) {
    const cors = getCorsHeaders(request.headers.get("origin"));

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: cors });
    }
    if (request.method !== "POST") {
      return new Response("Not allowed", { status: 405, headers: cors });
    }

    const key = env.GEMINI_API_KEY;
    if (!key) {
      return new Response(
        JSON.stringify({ error: "GEMINI_API_KEY not configured" }),
        {
          status: 500,
          headers: { "Content-Type": "application/json", ...cors },
        },
      );
    }

    let body: {
      messages?: Array<{ role: string; content: string }>;
      model?: string;
    };
    try {
      body = await request.json();
    } catch {
      return new Response(JSON.stringify({ error: "Invalid JSON" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...cors },
      });
    }

    const url = new URL(request.url);
    const model = url.searchParams.get("model") ?? body.model ?? DEFAULT_MODEL;
    if (!ALLOWED_MODELS.includes(model)) {
      return new Response(JSON.stringify({ error: "Model not allowed" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...cors },
      });
    }

    const geminiBody: Record<string, unknown> = {
      contents: toGeminiContents(body.messages ?? []),
    };
    if (SYSTEM_PROMPT) {
      geminiBody.systemInstruction = { parts: [{ text: SYSTEM_PROMPT }] };
    }

    const endpoint = `${GEMINI_BASE}/${model}:streamGenerateContent?alt=sse&key=${key}`;
    const upstream = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(geminiBody),
    });

    if (!upstream.ok) {
      const errText = await upstream.text();
      return new Response(
        JSON.stringify({
          error: `Gemini error ${upstream.status}: ${errText}`,
        }),
        {
          status: upstream.status,
          headers: { "Content-Type": "application/json", ...cors },
        },
      );
    }

    // Pipe the Gemini SSE stream directly to the client.
    return new Response(upstream.body, {
      status: 200,
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
        ...cors,
      },
    });
  },
};
